# Sequential model

In [1]:
import tensorflow as tf

## 建立模型結構

## 模型語法 1

In [2]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Input((28, 28)),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10, activation='softmax')
])

## 模型語法 2：將input_shape拿掉，以model參數設定

In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation='softmax')
])

x = tf.keras.layers.Input(shape=(28, 28))
# 或 x = tf.Variable(tf.random.truncated_normal([28, 28]))
y = model(x)

## 模型語法 3：可以直接串連神經層

In [4]:
layer1 = tf.keras.layers.Dense(2, activation="relu", name="layer1")
layer2 = tf.keras.layers.Dense(3, activation="relu", name="layer2")
layer3 = tf.keras.layers.Dense(4, name="layer3")

# Call layers on a test input
x = tf.ones((3, 3))
y = layer3(layer2(layer1(x)))

## 臨時加減神經層

In [5]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Input((28, 28)),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10, activation='softmax')
])

# 刪減一層
model.pop()
print(f'神經層數: {len(model.layers)}')
model.layers

神經層數: 3


[<Flatten name=flatten_2, built=True>,
 <Dense name=dense_4, built=True>,
 <Dropout name=dropout_2, built=True>]

In [6]:
# 增加一層
model.add(tf.keras.layers.Dense(10))
print(f'神經層數: {len(model.layers)}')
model.layers

神經層數: 4


[<Flatten name=flatten_2, built=True>,
 <Dense name=dense_4, built=True>,
 <Dropout name=dropout_2, built=True>,
 <Dense name=dense_6, built=True>]

## 取得模型及神經層資訊

In [9]:
# 建立 3 layers
layer0 = tf.keras.layers.Input((28, 28))
layer1 = tf.keras.layers.Dense(2, activation="relu", name="layer1")
layer2 = tf.keras.layers.Dense(3, activation="relu", name="layer2")
layer3 = tf.keras.layers.Dense(4, name="layer3")

# 建立模型
model = tf.keras.models.Sequential([
  layer0,
  layer1,
  layer2,
  layer3
])

# 讀取模型權重
print(f'神經層參數類別總數: {len(model.weights)}')
model.weights

神經層參數類別總數: 6


[<KerasVariable shape=(28, 2), dtype=float32, path=sequential_5/layer1/kernel>,
 <KerasVariable shape=(2,), dtype=float32, path=sequential_5/layer1/bias>,
 <KerasVariable shape=(2, 3), dtype=float32, path=sequential_5/layer2/kernel>,
 <KerasVariable shape=(3,), dtype=float32, path=sequential_5/layer2/bias>,
 <KerasVariable shape=(3, 4), dtype=float32, path=sequential_5/layer3/kernel>,
 <KerasVariable shape=(4,), dtype=float32, path=sequential_5/layer3/bias>]

In [10]:
print(f'{layer2.name}: {layer2.weights}')

layer2: [<KerasVariable shape=(2, 3), dtype=float32, path=sequential_5/layer2/kernel>, <KerasVariable shape=(3,), dtype=float32, path=sequential_5/layer2/bias>]


In [11]:
# 取得模型彙總資訊
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ layer1 (Dense)                       │ (None, 28, 2)               │              58 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ layer2 (Dense)                       │ (None, 28, 3)               │               9 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ layer3 (Dense)                       │ (None, 28, 4)               │              16 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 83 (332.00 B)

 Trainable params: 83 (332.00 B)

 Non-trainable params: 0 (0.00 B)

## 一邊加神經層，一邊顯示模型彙總資訊，以利除錯

In [12]:
from tensorflow.keras import layers

model = tf.keras.models.Sequential()
model.add(tf.keras.Input(shape=(250, 250, 3)))  # 250x250 RGB images
model.add(layers.Conv2D(32, 5, strides=2, activation="relu"))
model.add(layers.Conv2D(32, 3, activation="relu"))
model.add(layers.MaxPooling2D(3))

# 顯示目前模型彙總資訊
model.summary()

# The answer was: (40, 40, 32), so we can keep downsampling...

model.add(layers.Conv2D(32, 3, activation="relu"))
model.add(layers.Conv2D(32, 3, activation="relu"))
model.add(layers.MaxPooling2D(3))
model.add(layers.Conv2D(32, 3, activation="relu"))
model.add(layers.Conv2D(32, 3, activation="relu"))
model.add(layers.MaxPooling2D(2))

# 顯示目前模型彙總資訊
model.summary()

# Now that we have 4x4 feature maps, time to apply global max pooling.
model.add(layers.GlobalMaxPooling2D())

# Finally, we add a classification layer.
model.add(layers.Dense(10))

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                      │ (None, 123, 123, 32)        │           2,432 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_1 (Conv2D)                    │ (None, 121, 121, 32)        │           9,248 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d (MaxPooling2D)         │ (None, 40, 40, 32)          │               0 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 11,680 (45.62 KB)

 Trainable params: 11,680 (45.62 KB)

 Non-trainable params: 0 (0.00 B)

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                      │ (None, 123, 123, 32)        │           2,432 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_1 (Conv2D)                    │ (None, 121, 121, 32)        │           9,248 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d (MaxPooling2D)         │ (None, 40, 40, 32)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_2 (Conv2D)                    │ (None, 38, 38, 32)          │           9,248 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_3 (Conv2D)                    │ (None, 36, 36, 32)          │           9,248 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_1 (MaxPooling2D)       │ (None, 12, 12, 32)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_4 (Conv2D)                    │ (None, 10, 10, 32)          │           9,248 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_5 (Conv2D)                    │ (None, 8, 8, 32)            │           9,248 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_2 (MaxPooling2D)       │ (None, 4, 4, 32)            │               0 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 48,672 (190.12 KB)

 Trainable params: 48,672 (190.12 KB)

 Non-trainable params: 0 (0.00 B)

## 取得每一層神經層的output

In [13]:
# 設定模型
initial_model = tf.keras.Sequential(
    [
        tf.keras.Input(shape=(250, 250, 3)),
        layers.Conv2D(32, 5, strides=2, activation="relu"),
        layers.Conv2D(32, 3, activation="relu"),
        layers.Conv2D(32, 3, activation="relu"),
    ]
)

# 設定模型的 input/output
feature_extractor = tf.keras.Model(
    inputs=initial_model.inputs,
    outputs=[layer.output for layer in initial_model.layers],
)

# 呼叫 feature_extractor 取得 output
x = tf.ones((1, 250, 250, 3))
features = feature_extractor(x)
features

C:\Users\mikec\anaconda3\Lib\site-packages\keras\src\models\functional.py:225: UserWarning: The structure of `inputs` doesn't match the expected structure: ['keras_tensor_103']. Received: the structure of inputs=*
  warnings.warn(


[<tf.Tensor: shape=(1, 123, 123, 32), dtype=float32, numpy=
 array([[[[0.        , 0.        , 0.        , ..., 0.3272895 ,
           0.        , 0.        ],
          [0.        , 0.        , 0.        , ..., 0.3272895 ,
           0.        , 0.        ],
          [0.        , 0.        , 0.        , ..., 0.3272895 ,
           0.        , 0.        ],
          ...,
          [0.        , 0.        , 0.        , ..., 0.32728958,
           0.        , 0.        ],
          [0.        , 0.        , 0.        , ..., 0.32728958,
           0.        , 0.        ],
          [0.        , 0.        , 0.        , ..., 0.32728958,
           0.        , 0.        ]],
 
         [[0.        , 0.        , 0.        , ..., 0.3272895 ,
           0.        , 0.        ],
          [0.        , 0.        , 0.        , ..., 0.3272895 ,
           0.        , 0.        ],
          [0.        , 0.        , 0.        , ..., 0.3272895 ,
           0.        , 0.        ],
          ...,
       

In [14]:
# 設定模型
initial_model = tf.keras.Sequential(
    [
        tf.keras.Input(shape=(250, 250, 3)),
        layers.Conv2D(32, 5, strides=2, activation="relu"),
        layers.Conv2D(32, 3, activation="relu", name="my_intermediate_layer"),
        layers.Conv2D(32, 3, activation="relu"),
    ]
)

# 設定模型的 input/output
feature_extractor = tf.keras.Model(
    inputs=initial_model.inputs,
    outputs=initial_model.get_layer(name="my_intermediate_layer").output,
)

# 呼叫 feature_extractor 取得 output
x = tf.ones((1, 250, 250, 3))
features = feature_extractor(x)
features

C:\Users\mikec\anaconda3\Lib\site-packages\keras\src\models\functional.py:225: UserWarning: The structure of `inputs` doesn't match the expected structure: ['keras_tensor_107']. Received: the structure of inputs=*
  warnings.warn(


<tf.Tensor: shape=(1, 121, 121, 32), dtype=float32, numpy=
array([[[[0.10773948, 0.16486645, 0.        , ..., 0.        ,
          0.4314403 , 0.16374938],
         [0.10773948, 0.16486645, 0.        , ..., 0.        ,
          0.4314403 , 0.16374938],
         [0.10773948, 0.16486645, 0.        , ..., 0.        ,
          0.4314403 , 0.16374938],
         ...,
         [0.10773949, 0.16486648, 0.        , ..., 0.        ,
          0.4314404 , 0.16374941],
         [0.10773952, 0.16486645, 0.        , ..., 0.        ,
          0.4314404 , 0.16374947],
         [0.10773953, 0.16486646, 0.        , ..., 0.        ,
          0.43144044, 0.16374947]],

        [[0.10773948, 0.16486645, 0.        , ..., 0.        ,
          0.4314403 , 0.16374938],
         [0.10773948, 0.16486645, 0.        , ..., 0.        ,
          0.4314403 , 0.16374938],
         [0.10773948, 0.16486645, 0.        , ..., 0.        ,
          0.4314403 , 0.16374938],
         ...,
         [0.10773949, 0.16486