# 馬可夫鏈(Markov Chain) -- 晴天/雨天機率計算

## 載入套件

In [2]:
import numpy as np

## 晴天/雨天機率設定

In [3]:
p =np.array([0.8, 0.2, 0.1, 0.9]).reshape(2, 2)
p

array([[0.8, 0.2],
       [0.1, 0.9]])

## 矩陣運算

In [9]:
p @ p

array([[0.66, 0.34],
       [0.17, 0.83]])

## 驗算：今天是晴天，後天也是晴天的機率計算

In [5]:
0.8 * 0.8 + 0.2 * 0.1

0.6600000000000001

## 預測大後天

In [10]:
p @ p @ p

array([[0.562, 0.438],
       [0.219, 0.781]])