# LSTM重要參數測試

In [1]:
# 載入相關套件
import tensorflow as tf
from tensorflow.keras.layers import Dense, LSTM, Input
from tensorflow.keras.models import Sequential
import numpy as np

In [8]:
# 定義模型，參數均為預設值
model = Sequential()
model.add(Input((3, 1)))
model.add(LSTM(1))

# 測試資料
data = np.array([0.1, 0.2, 0.3]).reshape((1,3,1))
# 預測：只傳回最後的輸出(y)
print(model.predict(data))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step
[[0.05493739]]


## return_sequences=True

In [9]:
# 定義模型，參數 return_sequences=True
model = Sequential()
model.add(Input((3, 1)))
model.add(LSTM(1,return_sequences=True))

# 測試資料
data = np.array([0.1, 0.2, 0.3]).reshape((1,3,1))
# 預測：傳回每一節點的輸出(y)
print(model.predict(data))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step
[[[-0.00791939]
  [-0.02220181]
  [-0.0419028 ]]]


## return_state=True

In [4]:
# 定義模型，參數 return_state=True
# 多個輸出必須使用 Function API
from keras.models import Model

inputs1 = Input(shape=(3, 1))
lstm1 = LSTM(1, return_state=True)(inputs1)
model = Model(inputs=inputs1, outputs=lstm1)

# 測試資料
data = np.array([0.1, 0.2, 0.3]).reshape((1,3,1))
# 預測：傳回 輸出(y), state_h, state_c
print(model.predict(data))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step
(array([[0.08754116]], dtype=float32), array([[0.08754116]], dtype=float32), array([[0.1926644]], dtype=float32))


## return_sequences=True、return_state=True

In [5]:
# 定義模型，參數 return_sequences=True、return_state=True
# 多個輸出必須使用 Function API
from keras.models import Model

inputs1 = Input(shape=(3, 1))
lstm1 = LSTM(1, return_sequences=True, return_state=True)(inputs1)
model = Model(inputs=inputs1, outputs=lstm1)

# 測試資料
data = np.array([0.1, 0.2, 0.3]).reshape((1,3,1))
# 預測：傳回 輸出(y), state_h, state_c
print(model.predict(data))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step
(array([[[0.021248  ],
        [0.05260667],
        [0.085071  ]]], dtype=float32), array([[0.085071]], dtype=float32), array([[0.1932264]], dtype=float32))


## 模型包含2個LSTM神經層

In [6]:
# 定義模型，參數 return_sequences=True、return_state=True
# 多個輸出必須使用 Function API
from keras.models import Model

inputs1 = Input(shape=(3, 1))
lstm1 = LSTM(1, return_sequences=True)(inputs1)
lstm2 = LSTM(1, return_sequences=True, return_state=True)(lstm1)
model = Model(inputs=inputs1, outputs=lstm2)

# 測試資料
data = np.array([0.1, 0.2, 0.3]).reshape((1,3,1))
# 預測：傳回 輸出(y), state_h, state_c
print(model.predict(data))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 219ms/step
(array([[[0.00241356],
        [0.00783869],
        [0.01605479]]], dtype=float32), array([[0.01605479]], dtype=float32), array([[0.03084216]], dtype=float32))


## 第一個 LSTM 不加參數 return_sequences=True會有錯誤

In [7]:
# 多個輸出必須使用 Function API
from keras.models import Model

inputs1 = Input(shape=(3, 1))
lstm1 = LSTM(1)(inputs1)
lstm2 = LSTM(1, return_sequences=True, return_state=True)(lstm1)
model = Model(inputs=inputs1, outputs=lstm2)

# 測試資料
data = np.array([0.1, 0.2, 0.3]).reshape((1,3,1))
# 預測：傳回 輸出(y), state_h, state_c
print(model.predict(data))

ValueError: Input 0 of layer "lstm_7" is incompatible with the layer: expected ndim=3, found ndim=2. Full shape received: (None, 1)